name: Verify

on:
  push:
  pull_request:

jobs:
  test:
    strategy:
      matrix:
        os:
          - macos-26-intel
          - macos-26
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - run: swift script/style.swift
      - run: swift test
